/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_3ed1835c (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/grrmhkpzjvabntoozvio/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

const client = () => createClient(
  Deno.env.get("SUPABASE_URL"),
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_3ed1835c").upsert({
    key,
    value
  });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_3ed1835c").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_3ed1835c").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_3ed1835c").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_3ed1835c").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_3ed1835c").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
// PostgREST caps a single response at 1000 rows, so page through with range()
// — otherwise prefixes with >1000 keys (e.g. >1000 users) are silently truncated,
// which makes accounts past the 1000th invisible and unable to log in.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const PAGE = 1000;
  const out: any[] = [];
  for (let from = 0; ; from += PAGE) {
    const { data, error } = await supabase
      .from("kv_store_3ed1835c")
      .select("key, value")
      .like("key", prefix + "%")
      .order("key")
      .range(from, from + PAGE - 1);
    if (error) {
      throw new Error(error.message);
    }
    if (!data || data.length === 0) break;
    for (const d of data) out.push(d.value);
    if (data.length < PAGE) break;
  }
  return out;
};

// Search and return raw {key, value} pairs by prefix.
export const getEntriesByPrefix = async (prefix: string): Promise<Array<{ key: string; value: any }>> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_3ed1835c").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data ?? [];
};

// Delete every key matching a prefix.
export const delByPrefix = async (prefix: string): Promise<number> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_3ed1835c").delete().like("key", prefix + "%").select("key");
  if (error) {
    throw new Error(error.message);
  }
  return data?.length ?? 0;
};